### ISSUE TITLE
YoloX+GStreamer not working

### ISSUE THREAD

**Issue by velv01** [Qengineering/YoloX-ncnn-Raspberry-Pi-4#1]
I'm getting a error while trying to build the project.
Here's the output 

[1:32:36.474027174] [18893]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/ov5647@36 to Unicam device /dev/media1 and ISP device /dev/media2
[1:32:36.484413505] [18896]  INFO Camera camera.cpp:1033 configuring streams: (0) 1280x720-NV21
[1:32:36.485093962] [18893]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/ov5647@36 - Selected sensor format: 1920x1080-SGBRG10_1X10 - Selected unicam format: 1920x1080-pGAA
[ WARN:0@0.855] global cap_gstreamer.cpp:1697 open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0@0.855] global cap_gstreamer.cpp:1728 open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
fopen yoloxS.param failed
fopen yoloxS.bin failed
Hit ESC to exit
find_blob_index_by_name images failed
Try
find_blob_index_by_name output failed
Try
Segmentation fault

Process returned 139 (0x8B)   execution time : 1.160 s
Press ENTER to continue.

Please help to resolve the issue

PS: I'm using the 64bit bullseye release on pi4 with rpicam v1

**Comment by Qengineering** [comment]
@velv01,

The key to your issue are the sentences:
```cpp
fopen yoloxS.param failed
fopen yoloxS.bin failed
```
In other words the app can't find the ncnn deep learning models.

In lines 396 and 397 in YoloX.cpp you find the hardcoded location the app will look for the models.
```cpp
    yolox.load_param("yoloxS.param");
    yolox.load_model("yoloxS.bin");
```
Running form a console, the models need to be in the same folder as the app.
Running in the IDE of Code::Blocks they need to be in the working directory.

**Comment by velv01** [comment]
Thanks for the support...it works now.

**Comment by Qengineering** [comment]
Good to hear
